### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by joseywoermann** [joseywoermann/PyStore#1]
1. stock
2. finance
3. ordering
4. delivery
5. limited stock
6. outsourcing into files

**Comment by therealmistericraft** [comment]
What the hell is this?

**Comment by joseywoermann** [comment]
> What the hell is this?

Huh? Look at the description.

**Comment by therealmistericraft** [comment]
But you are under aged, you don't have articles to sale, ...

**Comment by joseywoermann** [comment]
You know what the word "_virtual_" means, right?

**Comment by joseywoermann** [comment]
done
